# Generated by Django 3.2.2 on 2022-09-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(help_text='nombre de clientes', max_length=200, verbose_name='nombres')),
                ('apellidos', models.CharField(help_text='apellidos de clientes', max_length=254, verbose_name='apellidos')),
                ('numero_identidad', models.CharField(help_text='numero identidad', max_length=10, verbose_name='numero de identidad')),
                ('fecha_nacimiento', models.DateField(blank=True, help_text='fecha de nacimiento', max_length=11, null=True, verbose_name='fecha de namiento')),
                ('ingreso_mensual', models.DecimalField(blank=True, decimal_places=2, help_text='monto de ingrso', max_digits=10, null=True, verbose_name='monto de ingreso')),
            ],
            options={
                'verbose_name': 'Clientes',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
            },
        ),
    ]
