# Generated by Django 3.2.2 on 2022-10-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=200, verbose_name='nombres')),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='precio de producto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
            },
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellidos',
            field=models.CharField(max_length=254, verbose_name='apellidos'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, max_length=11, null=True, verbose_name='fecha de namiento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ingreso_mensual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='monto de ingreso'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombres',
            field=models.CharField(max_length=200, verbose_name='nombres'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero_identidad',
            field=models.CharField(max_length=10, verbose_name='numero de identidad'),
        ),
    ]
