# Generated by Django 3.2.2 on 2022-10-03 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20221003_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facturas', models.CharField(max_length=200, verbose_name='nombres de factura')),
                ('fecha_venta', models.DateField(blank=True, max_length=11, null=True, verbose_name='fecha de venta')),
                ('cliente_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente')),
                ('producto_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.producto')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'ventas',
            },
        ),
    ]
